# Jeff Jojer Jones E. Catulay
BSCS 3B

# MIDTERM LAB EXAM:
1.) Use sales-data sheet from assignment-data.xlsx on your existing dataset and
do the following tasks:
The Managing Director found that there is no clarity in sales-data. He likes to see
clear visualization of data in various dimensions. He instructed his junior data
scientist “Mr.Bean” to reshape the data.
# Part-1:
Mr.Bean decided to display the product details produced by every company, along
with supervisor detail. [ Hint: Use Pivot Table]. The expected output is as follows:

In [2]:
# import library
# pip install pandas
# pip install numpy
import pandas as pd, numpy as np

In [3]:
# load the specific excel file and sheet name
# pip install pyexcel
df = pd.read_excel('assignment-data.xlsx', sheet_name='sales-data')
df

Account-no company-name co-supervisor      supervisor Product-detail  \
0        A300        Apple         Julia    Peter Prince  search engine   
1        A300        Apple         Julia    Peter Prince       Software   
2        A300        Apple         Julia    Peter Prince        printer   
3        A301       Google         Julia    Peter Prince  search engine   
4        A302     Facebook      Mary Lim    Peter Prince  search engine   
5        A304          HCL      Mary Lim    Peter Prince  search engine   
6        A304          HCL      Mary Lim    Peter Prince       Software   
7        A304          HCL         Jason    Peter Prince        printer   
8        A305      ABC ltd         Jason    Peter Prince  search engine   
9        A306          SAP      Isabella  David Anderson  search engine   
10       A307        Adobe      Isabella  David Anderson  search engine   
11       A308  XYZ company      Isabella  David Anderson        printer   
12       A308  XYZ company      Isabella  David Anderson       Software   
13       A309    Microsoft        Xavier  David Anderson        printer   
14       A310       Oracle        Xavier  David Anderson  search engine   
15       A311      Infosys        Xavier  David Anderson  search engine   
16       A312      Infosys        Xavier  David Anderson        Monitor   

    total-quantity  Price         Status  
0                2  40000       Finished  
1                2  20000       Finished  
2                3   6000  yet to finish  
3                2  45000       declined  
4                3  54000            won  
5                3  43000  yet to finish  
6                2  12000       Finished  
7                3   8000  yet to finish  
8                2  25000       declined  
9                3  75000            won  
10               2  23000  yet to finish  
11               2   3000  yet to finish  
12               2   9000       Finished  
13               4   5000            won  
14               6  90000            won  
15               3  69000       declined  
16               3   4000       Finished

In [109]:
table_value = pd.pivot_table(df, values='Price', index=['supervisor', 'company-name'],
                    columns=['Product-detail'], aggfunc=np.sum, fill_value=0)

In [110]:
table_value

Product-detail               Monitor  Software  printer  search engine
supervisor     company-name                                           
David Anderson Adobe               0         0        0          23000
               Infosys          4000         0        0          69000
               Microsoft           0         0     5000              0
               Oracle              0         0        0          90000
               SAP                 0         0        0          75000
               XYZ company         0      9000     3000              0
Peter Prince   ABC ltd             0         0        0          25000
               Apple               0     20000     6000          40000
               Facebook            0         0        0          54000
               Google              0         0        0          45000
               HCL                 0     12000     8000          43000

# Part 2:
Mr.Bean decided to show the top 5companies that have the most 'total-quantity'
ordered.

In [111]:
count_item=df.groupby('company-name').sum().sort_values('total-quantity', ascending=False).reset_index()
count_item.iloc[0:5, 0:2]

company-name  total-quantity
0          HCL               8
1        Apple               7
2      Infosys               6
3       Oracle               6
4    Microsoft               4

# Part 3:
Further, “Mr.Bean” needs to show the total-quantity vs Price for 3 companies
Apple, HCL and Infosys

In [122]:
res =df.sort_values(by=['total-quantity', 'Price'])
apple = res[res['company-name'] == "Apple"]
apple

Account-no company-name co-supervisor    supervisor Product-detail  \
1       A300        Apple         Julia  Peter Prince       Software   
0       A300        Apple         Julia  Peter Prince  search engine   
2       A300        Apple         Julia  Peter Prince        printer   

   total-quantity  Price         Status  
1               2  20000       Finished  
0               2  40000       Finished  
2               3   6000  yet to finish

In [123]:
hcl = res[res['company-name'] == "HCL"]
hcl

Account-no company-name co-supervisor    supervisor Product-detail  \
6       A304          HCL      Mary Lim  Peter Prince       Software   
7       A304          HCL         Jason  Peter Prince        printer   
5       A304          HCL      Mary Lim  Peter Prince  search engine   

   total-quantity  Price         Status  
6               2  12000       Finished  
7               3   8000  yet to finish  
5               3  43000  yet to finish

In [124]:
infosys = res[res['company-name'] == "Infosys"]
infosys

Account-no company-name co-supervisor      supervisor Product-detail  \
16       A312      Infosys        Xavier  David Anderson        Monitor   
15       A311      Infosys        Xavier  David Anderson  search engine   

    total-quantity  Price    Status  
16               3   4000  Finished  
15               3  69000  declined

# 1

In [114]:
print("Creating 8X4 array using numpy.arrange")
sampleArray = np.arange(20,52,1)
sampleArray = sampleArray.reshape(8,4)
print(sampleArray)

Creating 8X4 array using numpy.arrange
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]]


In [119]:
value = [24, 54, 67, 89, 10, 2, 5, 12]
np.insert(value, 0, 3)

array([ 3, 24, 54, 67, 89, 10,  2,  5, 12])

# 2

In [121]:
square = np.sqrt([sampleArray])
square

array([[[4.47213595, 4.58257569, 4.69041576, 4.79583152],
        [4.89897949, 5.        , 5.09901951, 5.19615242],
        [5.29150262, 5.38516481, 5.47722558, 5.56776436],
        [5.65685425, 5.74456265, 5.83095189, 5.91607978],
        [6.        , 6.08276253, 6.164414  , 6.244998  ],
        [6.32455532, 6.40312424, 6.4807407 , 6.55743852],
        [6.63324958, 6.70820393, 6.78232998, 6.8556546 ],
        [6.92820323, 7.        , 7.07106781, 7.14142843]]])

# 3

In [125]:
newarr = np.array_split(sampleArray, 4)
newarr

[array([[20, 21, 22, 23],
        [24, 25, 26, 27]]),
 array([[28, 29, 30, 31],
        [32, 33, 34, 35]]),
 array([[36, 37, 38, 39],
        [40, 41, 42, 43]]),
 array([[44, 45, 46, 47],
        [48, 49, 50, 51]])]

# 4

In [127]:
arr = np.delete(sampleArray, 3)
arr

array([20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51])

# 5

In [128]:
list(arr.flat)

[20,
 21,
 22,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51]